version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: socket-io-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: socket_io_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - socket-io-network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: socket-io-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - socket-io-network

volumes:
  postgres_data:

networks:
  socket-io-network:
    driver: bridge 